name: Build

on: [push, pull_request]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [windows-latest, ubuntu-latest]
                node-version: [14]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3
              with:
                  lfs: ${{ startsWith(github.ref, 'refs/tags/v') }}

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint-check

            - name: Format
              run: npm run format-check

            - name: Electron Builder Action
              uses: samuelmeuli/action-electron-builder@v1.6.0
              with:
                  # GitHub token, automatically provided to the action
                  # (No need to define this secret in the repo settings)
                  github_token: ${{ secrets.github_token }}
                  # If the commit is tagged with a version (e.g. "v1.0.0"),
                  # release the app after building
                  release: ${{ startsWith(github.ref, 'refs/tags/v') }}
                  skip_build: true
